// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtydlbpwbjcxwiysleei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0eWRsYnB3YmpjeHdpeXNsZWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDM3MTEsImV4cCI6MjA2MTM3OTcxMX0.gdPS_FqPnPIHp3WKq0fMvdjwbCmpMNLuJ1o7lIVbZmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);